import { useState } from 'react'
import { Bike, CheckCircle2, ChevronRight, Clock3, MapPin, Navigation, Power, Route, Users, Wallet } from 'lucide-react'

type TripState = 'available' | 'accepted' | 'riding' | 'complete'
export default function App() {
  const [online, setOnline] = useState(true)
  const [trip, setTrip] = useState<TripState>('available')
  const next = () => setTrip((state) => state === 'available' ? 'accepted' : state === 'accepted' ? 'riding' : state === 'riding' ? 'complete' : 'available')
  const action = trip === 'available' ? 'Accept cluster' : trip === 'accepted' ? 'Start pickup' : trip === 'riding' ? 'Complete trip' : 'Find next cluster'
  return <main className="driver-shell"><header><div className="avatar">RK</div><div><small>GOOD EVENING</small><h1>Rakesh Kumar</h1></div><button className={`online ${online ? '' : 'off'}`} onClick={() => setOnline(!online)}><Power size={15}/>{online ? 'Online' : 'Offline'}</button></header><section className="map"><div className="map-label"><Navigation size={16}/><span>Near Aluva Metro</span></div><span className="pin one"/><span className="pin two"/><span className="route-line"/><div className="map-status"><span className="pulse"/> {online ? 'Looking for nearby clusters' : 'You are offline'}</div></section><section className="content"><div className="earnings"><div><small>TODAY’S EARNINGS</small><strong>₹840</strong><p>8 trips · ₹160 to bonus</p></div><Wallet size={25}/></div>{trip === 'complete' ? <section className="completed"><CheckCircle2 size={42}/><h2>Trip completed</h2><p>₹132 added to your wallet.</p></section> : <><div className="section-title"><div><small>ORBIT CLUSTER</small><h2>{trip === 'available' ? 'A route that fits' : trip === 'accepted' ? 'Head to the station' : 'On the way together'}</h2></div><span className="cluster">3 <Users size={14}/></span></div><section className="cluster-card"><div className="cluster-top"><span className="trip-icon"><Bike size={20}/></span><div><strong>Aluva → Kakkanad</strong><p><Clock3 size={13}/> 24 min · 8.2 km</p></div><span className="price">₹132</span></div><div className="route-steps"><p><i/> Aluva Metro · South gate</p><p><i/> Infopark Phase 1 · 3 drop-offs</p></div><div className="riders"><span>AN</span><span>SM</span><span>+1</span><p>3 riders are ready at the pickup zone</p></div></section><button disabled={!online} className="primary" onClick={next}>{action}<ChevronRight size={20}/></button><button className="nav-button"><Route size={18}/> Open navigation</button></>}</section><nav><button><MapPin size={19}/><span>Trips</span></button><button><Clock3 size={19}/><span>History</span></button><button><Wallet size={19}/><span>Wallet</span></button></nav></main>
}
